#27: [poc] stato new api (closes #27)
buildo/state pull request #28
Opened 2017-05-23 16:18 UTC by francescogior

Closes #27

## Test Plan

### tests performed
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

### tests not performed (domain coverage)
> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

2017-06-16 15:06 UTC, giogonzo requested changes
just a comment inline (also I pushed a very minor commit)

2017-06-16 15:06 UTC, giogonzo commented on src/connect.js
> +  });
this should be wrapped in an `if (isKeyList)`?

2017-06-23 09:27 UTC, veej commented on src/connect.js
> +  });
yep 👍 
fixed

2017-06-23 11:14 UTC, giogonzo approved these changes

2017-06-23 11:14 UTC, merged