#39: Parse and stringify state params based on state type (closes #39)
buildo/state pull request #40
Opened 2017-08-11 12:20 UTC by francescogior

Closes #39

## Test Plan

### tests performed
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

### tests not performed (domain coverage)
> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

2017-08-11 15:01 UTC, FrancescoCioria commented
@francescogior as of today the stringification/parsing of params is done by `state-react-router` outside of `buildo-state`. You're doing it here because we're planning to kill `state-react-router`?

2017-08-11 15:04 UTC, FrancescoCioria requested changes

2017-08-11 15:04 UTC, FrancescoCioria commented on src/run.js
> +      const wroteToRouter = syncToBrowser(stringifyParams(state), stringifyParams(newState));
`syncToBrowser` expects the two original state objects, if you stringify them you break it (this is why the tests are failing)

In order to use `stringifyParams` inside `buildo-state` I think we should remove or seriously re-think `syncToBrowser`.

An option for now could be exporting `stringifyParams` as a util to be used in the project.

2017-08-21 14:48 UTC, giogonzo commented
as discussed offline, closing in favor of #41

2017-08-21 14:48 UTC, closed without merging